# Generated by Django 4.2.4 on 2024-03-21 05:23

import course.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, validators=[course.validators.validate_title])),
                ('category', models.CharField(choices=[('Math', 'math'), ('Database', 'database'), ('Artificial Intelegence', 'artificial_intelegence'), ('Internet of Things', 'internet_of_things')], default='Math', max_length=255)),
                ('description', models.TextField()),
                ('timestamps', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(editable=False, max_length=255, unique=True)),
            ],
        ),
    ]
